"""build_report — fold the stage outputs into one self-contained HTML report.

    python tools/sim/build_report.py [--out path.html]

Reads tools/sim/out/stages/{catalog,calibrate,baseline,picks,mods,greedy}.json (any missing stage
is simply left out of the page) and writes tools/sim/out/report.html by inlining the data into
tools/sim/report_template.html.

Findings are generated by fixed rules (below), not written by hand, so re-running the sweep after
a balance change re-derives them. The one exception is MANUAL_FINDINGS: facts found while
building the harness that no stage measures directly.
"""
from __future__ import annotations

import json
import math
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from report_graphs import dep_graph, mod_network  # noqa: E402
STAGES = HERE / "out" / "stages"
for _a in sys.argv[1:]:
    if _a.startswith("--stages="):   # build from an archived stage set, e.g. out/stages_interim
        STAGES = Path(_a.split("=", 1)[1])
TEMPLATE = HERE / "report_template.html"

ARENAS = ["single", "cluster", "horde", "pressure"]
SEV_ORDER = {"bug": 0, "decision": 1, "fixed": 2, "warn": 3, "info": 4, "caveat": 5}
## Picks whose measured value was inflated by the (now fixed) on-crit proc chain. Empty since the
## TriggerComponent re-entrancy guard landed; kept so an interim report built from pre-fix stage
## data can still be tagged (--stages=out/stages_interim sets it back).
PROC_CHAIN_PICKS: set[str] = set()

## Found by hand while validating the harness — see the "reconcile" notes in the session log and
## sim_meter.gd. Kept here so they ride along with every regenerated report until resolved.
MANUAL_FINDINGS = [
    {
        "severity": "info",
        "title": "By design: crit procs fire on every crit in the kit, ticks included",
        "body": ("A crit proc gets its roll on every crit the character lands (swings, projectiles, "
                 "damage-over-time and ground-zone ticks), and a guaranteed proc fires on each one. "
                 "Ben, 2026-09-27: that is fun build-around play to unlock. The only thing that "
                 "cannot happen any more is a proc re-triggering itself from its own hits. Expect "
                 "crit-proc builds on fast-ticking kits to rank very high here: a Scavenger with "
                 "Caltrops, Static Discharge, Precision x2 and Assassin measured ~11x baseline pack "
                 "damage in a spot check."),
        "where": "data/factories/status_factory.gd:503 (static_discharge) · scripts/components/trigger_component.gd",
    },
    {
        "severity": "fixed",
        "title": "Fixed: Static Discharge could chain itself into a stack overflow",
        "body": ("Its on-crit lightning could itself crit and re-fire the same listener synchronously, "
                 "inside the same call. With enough crit and a tight pack the chain never ended: a "
                 "30-second fight overflowed the GDScript stack every frame and wrote a 10.6 GB error "
                 "log. TriggerComponent now keeps the set of listeners currently executing and skips "
                 "any listener already on it, so no proc can re-trigger itself through its own "
                 "consequences, directly or through a cycle of other procs. Separate events still fire "
                 "it every time, and other procs still react to its hits. Verified: the exact build "
                 "that overflowed now completes normally. Lightning Reflexes is covered by the same guard."),
        "where": "scripts/components/trigger_component.gd (_dispatching)",
    },
    {
        "severity": "fixed",
        "title": "Changed: crits are 2.0× at base, and crit damage stacks from there",
        "body": ("DamageCalculator used raw × (1 + crit_multiplier) on a 1.5 base, so every crit was "
                 "2.5× while the docs said 1.5×. The stat is now the multiplier itself — "
                 "raw × crit_multiplier, floored at 1× — and the base is 2.0 (Ben, 2026-09-27). Every "
                 "crit-damage source adds to it, uncapped: Precision +0.25 per rank (5 ranks), Assassin "
                 "+1.00, Glass Cannon +0.50, the Spark's passive +0.75 (→ 2.75×, passive text updated), "
                 "the Whisper's +0.25, plus weapons, trinkets, class mods and passive-tree nodes. Healing "
                 "crits follow the same rule. Verified: base crits ×2.0 (26.25 → 52.5), Precision ×2 "
                 "×2.5 (26.25 → 65.63), the Spark ×2.75 (7.2 → 19.8)."),
        "where": "scripts/entities/player.gd BASE_STATS · scripts/systems/damage_calculator.gd step 8 · data/characters.gd (Spark passive text) · docs/core_framework_decisions.md",
    },
    {
        "severity": "fixed",
        "title": "Fixed: player knockback compounded every frame",
        "body": ("player.gd added knockback_velocity into the persistent velocity each frame, so a "
                 "decaying shove was re-added on top of itself: a 584 push reached ~6,000 px/s and "
                 "carried the player ~780 px. Knockback is now applied to one frame's motion only; the "
                 "same push now moves the player 124 px, matching the physics (584² / 2·1400 ≈ 122). "
                 "Most contact knockback is blocked by the i-frames take_damage sets, but a Guard block, "
                 "Reckoning's dome and the Aegis shield return before i-frames, so it did reach play there."),
        "where": "scripts/entities/player.gd (_physics_process movement)",
    },
    {
        "severity": "fixed",
        "title": "Retracted: 'Tempest Vortex throws the Sellsword across the arena'",
        "body": ("An earlier version of this report called this a mod bug. It was the harness: the clear "
                 "arena kept the player immune with god_mode, which skips take_damage — and so the "
                 "i-frames that block contact knockback in real play — and every shove from the pulled "
                 "pack landed, compounded by the knockback bug above. The arena now uses death "
                 "prevention with the real hit path. No change was made to the mod. What it is worth "
                 "depends on how the Sellsword is played: his best clear rotation (one light, then "
                 "heavy, 168 kills/min) runs the Uppercut → Cataclysm string and rarely reaches Tempest, "
                 "so the sweep measures the mod as neutral there. Played as light chains, where every "
                 "loop ends in Tempest, it lifted clear speed from 85 to 228 kills/min in a spot check "
                 "(~2.7×), paid for in damage taken."),
        "where": "tools/sim/sim_arena.gd (horde immunity) · data/class_mods.gd:53",
        "kit": "The Drifter",
    },
    {
        "severity": "fixed",
        "title": "Fixed: zero-damage enemies shoved and flinched the player on touch",
        "body": ("enemy._on_hurtbox_body_entered ran a 0-damage take_damage (i-frames, hit flash, damage "
                 "animation) and a 160 contact shove whenever the player touched an enemy, without the "
                 "contact_damage > 0 check the sustained-contact path has. Real enemies affected: the "
                 "Herald, which chases the player with 0 contact damage, and the Carrier when you run into "
                 "it; also Training Room dummies with HIT BACK off. Now gated the same as the sustained path."),
        "where": "scripts/entities/enemy.gd (_on_hurtbox_body_entered)",
    },
    {
        "severity": "fixed",
        "title": "Fixed: armor from level-ups did nothing (Vitality, Juggernaut)",
        "body": ("player.apply_stat_upgrade filed '+N Armor' as (\"armor\", \"add\"), which nothing reads; "
                 "damage and get_armor() read (\"Physical\", \"resist\"). One shared stat→modifier mapping "
                 "(player._upgrade_modifier_key) now serves apply_stat_upgrade, remove_stat_upgrade and "
                 "apply_ability_upgrade, and ModifierComponent's dead-pair guard flags any (\"armor\", …) "
                 "modifier. Verified: Vitality gives 3 armor and 120 HP; Vitality ×2 → Juggernaut gives 12 "
                 "armor and 180 HP."),
        "where": "scripts/entities/player.gd (_upgrade_modifier_key) · scripts/components/modifier_component.gd",
    },
    {
        "severity": "fixed",
        "title": "Fixed: Glass Cannon and Velocity kept the Might damage they consume",
        "body": ("Percent damage is applied under \"All\" but remove_stat_upgrade looked for \"damage\", so "
                 "evolutions that consume Might never took its +15% back. Verified on the Sellsword opener "
                 "(22.5): Glass Cannon now hits 34.88 (×1.55, was 41.63), Velocity 25.87 (×1.15)."),
        "where": "scripts/entities/player.gd (remove_stat_upgrade)",
    },
    ## ── Deadeye pass (2026-09-29) ─────────────────────────────────────────────────────────────
    {
        "severity": "fixed",
        "title": "Fixed: six \"+X% damage\" self-buffs never reached a combo or skill hit",
        "body": ("They filed their modifier as (\"damage\", \"bonus\"), which only moves "
                 "get_stat(\"damage\"): pets, Holy Hammers and a few host-side hits read it. Combo and "
                 "skill hits bake the weapon's damage in at build time and take percentages in "
                 "DamageCalculator step 3, which reads (\"All\", \"bonus\"). Reload, Battle Fury, Honed "
                 "Edge, Extract Power and the passives Calm Hands and Bloodrage all showed as active and "
                 "changed nothing. All six use (\"All\", \"bonus\") now; the Ravager, Whisper and Cursed "
                 "got stronger with the Deadeye."),
        "where": "data/factories/chain_factory.gd (_timed_damage_buff, _blood_power_buff) · scripts/entities/player.gd (_update_bloodrage, _update_calm_hands)",
    },
    {
        "severity": "fixed",
        "title": "Fixed: a piercing seeker circled its first target instead of moving on",
        "body": ("ProjectileManager kept a homing lock until the target died, so a seeking shot with "
                 "pierce turned back onto the body it had just passed through and orbited it until it "
                 "expired. Pierce never landed a second hit on any seeking shot: Scavenger arrows with "
                 "Volley, and the Deadeye's storm and fan bullets. The lock now drops once the target is "
                 "on the shot's hit list, and bodies already hit are skipped when picking the next one."),
        "where": "scripts/systems/projectile_manager.gd (_acquire_seek_target)",
    },
    {
        "severity": "decision",
        "title": "Deadeye: Desert Storm is the pack tool, base HP 100, Fan the Hammer kept",
        "body": ("Ben, 2026-10-01. Desert Storm 3 → 5 bullets a tick, pierce 1 → 2, 0.75 → 0.82× per "
                 "bullet: at level 1 it beats the light-into-Fan route by +13% pack DPS (378 vs 335) and "
                 "+10% clear speed (155 vs 141 kills/min) and ties it on one target (186 vs 188). Pierce 2 "
                 "only pays against moving packs; rooted dummies rarely leave a third body in a bullet's "
                 "cone. Base HP 85 → 100 for survival. Fan the Hammer stays at 0.60× a bullet, so the "
                 "Deadeye keeps its #1 single-target spot (Ben chose that over a trim to 0.50×)."),
        "where": "data/factories/chain_factory.gd (build_gunslinger_desert_storm, _storm_bullets) · data/characters.gd",
        "kit": "The Deadeye",
    },
    ## ── Spark pass (2026-10-01) ───────────────────────────────────────────────────────────────
    {
        "severity": "fixed",
        "title": "Fixed: gameplay timers ran on the wall clock",
        "body": ("The Fireball charge, the Cursed's blood pools, the Berserker's Cadence cooldown and every "
                 "proc's internal cooldown read Time.get_ticks_msec(), so they kept running through hitstop "
                 "(every finisher freezes the game for 6 frames) and pause, and ran 4× short in the Training "
                 "Room's slow-mo. The balance sim runs about 10× real time, which made it obvious: a full "
                 "1.6 s Fireball charge read as ~0.15 s (×1.1 instead of ×2.0), blood pools lasted ~10× their "
                 "duration (the Cursed's survival was inflated), and Volatile Remains (0.25 s cooldown), "
                 "Glacial Guard (2 s), Pyre and Bulwark fired about a tenth as often as in a run. The player "
                 "now keeps a game-time clock (sum of the scaled physics delta), and TriggerComponent's "
                 "cooldown gate reads the orchestrator's run_time. Same bug CombatInputBuffer already fixed "
                 "for the input buffer."),
        "where": "scripts/entities/player.gd (_game_time) · scripts/components/trigger_component.gd (internal cooldown gate)",
    },
    {
        "severity": "fixed",
        "title": "Fixed: a charged Fireball threw away every mod on its release phase",
        "body": ("At the release, player.gd replaced the phase's projectile with a fresh one from "
                 "ChainFactory._wizard_fireball, scaled by the charge. Whatever a class mod or level-up had "
                 "done to that phase was discarded on every charged cast: FIREBALL EXPANSION's +35% blast and "
                 "SCORCHED EARTH's Burning never reached a Fireball. The host now scales the phase's own "
                 "projectile. Verified: Expansion's blast splashes all five other dummies of a pack instead "
                 "of three, and Scorched Earth's Burning ticks."),
        "where": "scripts/entities/player.gd (choreo_fire_effects, _scaled_hits)",
        "kit": "The Spark",
    },
    {
        "severity": "fixed",
        "title": "Fixed: Q and E ignored cooldown reduction",
        "body": ("SkillComponent set a skill's cooldown straight from cooldown_base. Only AbilityComponent "
                 "(auto-attacks, enemies) applied (\"All\", \"cooldown_reduce\"), and the player's combo graphs "
                 "carry no cooldown, so every source of it was dead: MANABURN (Spark), DARK HASTE (Shade), "
                 "RELENTLESS VOW (Warden), the evolution ABSOLUTE ZERO, and the Shade's Tome of the Restless "
                 "and Soulcage Scepter. Skills now apply it the same way (50% cap), and the HUD's cooldown "
                 "veil measures against the reduced duration. Verified: Dark Haste gives the Shade one more "
                 "Q and one more E per minute."),
        "where": "scripts/components/skill_component.gd (trigger, _cooldown_reduction) · scripts/ui/hud.gd",
    },
    {
        "severity": "fixed",
        "title": "Fixed: blue and purple weapons' \"+% damage\" lines did nothing",
        "body": ("Ten class weapons carried {\"tag\": \"damage\", \"op\": \"bonus\"}, the same dead pair as "
                 "the self-buffs above: Bloodsworn Greatblade, Emberfocus Rod, Cinderbrand, Grimoire of the "
                 "Nine Pits, Sceptre of the Archfiend, Stormforged Axe, Skullcleaver, Heart-Eater, World-Root "
                 "and Pyre of Judgment. They use (\"All\", \"bonus\") now. The sweep measures green weapons "
                 "only, so it could not see this."),
        "where": "data/weapons.gd (get_weapon_modifiers note)",
    },
    {
        "severity": "fixed",
        "title": "Fixed: TEMPEST CALL scaled a cosmetic pulse, not Storm Call",
        "body": ("The class mod scaled the storm_cast phase, whose only effect is a 0.2× self-pulse that "
                 "exists to fire the host hook. The strike itself (1.6× weapon damage per enemy, the whole "
                 "field) lives in player._storm_strike, which no phase op reaches, so the mod measured 1.00 "
                 "in every arena. Same bug the old Tempest Call pick had. It is a +0.32 storm_damage "
                 "modifier now (+20% on 1.6), Rising Storm's seam; \"45% broader\" left the card because the "
                 "strike already covers the field. Verified: strikes 40 → 48 on the green weapon."),
        "where": "data/class_mods.gd (wizard_tempest_call)",
        "kit": "The Spark",
    },
    {
        "severity": "fixed",
        "title": "Fixed: DEEPER PACT, SANGUINE DRAIN and GREATER PACT used the pets-only damage pair",
        "body": ("All three are \"+X% damage\" class mods filed as (\"damage\", \"bonus\"). None is pet-only, so "
                 "they use (\"All\", \"bonus\") now; the Blood Elemental and the Angry Demon strike with the "
                 "player as attacker, so they keep the bonus. Verified: Deeper Pact +7% Cursed single-target "
                 "DPS. (EMBER FAMILIAR keeps the pets-only pair on purpose.)"),
        "where": "data/class_mods.gd",
    },
    {
        "severity": "fixed",
        "title": "Fixed: Elemental Wards granted resist to a damage type that does not exist",
        "body": ("The passive-tree node gave +8 \"Cold\" resist. The engine's cold damage type is \"Ice\" "
                 "(\"cryo\" weapons map to it), and nothing deals \"Cold\", so a third of the node did "
                 "nothing. The passive tree is outside the sweep."),
        "where": "data/passive_tree.gd (a_wards)",
    },
    {
        "severity": "decision",
        "title": "Spark: standard weapon line, Fireball is the pack tool, a familiar that pays, HP 70",
        "body": ("Ben, 2026-10-01. The wizard line was 8/11/13 against the standard 25/34/40, the same gap the "
                 "Deadeye had. The Fireball's charge curve went from ×1.0–×2.0 to ×0.25–×2.0: every cast pays "
                 "~0.5 s that charging does not buy back, so at ×1.0 a 0.4 s hold out-damaged a full charge "
                 "by ~2×. Direct 1.1 → 4.0×, splash 0.9 → 2.75×, blast 34 → 40 px. At level 1 a full charge "
                 "deals 446 pack DPS against 398 for the light chain; the light chain keeps single target "
                 "(122 vs 97) and clear speed, and the 40% charge slow is the price. The familiar bites for "
                 "1.0× weapon damage (was 0.5×, a net loss once the summon interrupted the chain). Base HP "
                 "60 → 70 (tied with the Whisper for lowest). OVERLOAD BOLTS' card now says what it does "
                 "(staff bolts and the Fire Burst); reaching the Fireball waits for the class-mod pass."),
        "where": "data/weapons.gd · data/factories/chain_factory.gd (_wizard_fireball) · scripts/entities/player.gd (FIREBALL_MULT_MIN) · scripts/entities/fire_familiar.gd · data/characters.gd · data/class_mods.gd",
        "kit": "The Spark",
    },
    {
        "severity": "warn",
        "title": "Open for the class-mod pass: three cards still promise more than they do",
        "body": ("GLACIAL CAST (\"Ice freezes a +35% wider circle\") widens Frost Burst's damage (58 → 78 px) "
                 "but not its chill: choreo_fire_effects applies every phase status within a fixed 90 px. "
                 "SCORCHED EARTH (\"ignites every target it touches\") burns only the body the Fireball "
                 "strikes, not the splash. SANGUINE DRAIN (\"+18% damage increases each Vampirize beat's "
                 "yield\") is a plain +18% damage now, but the drain heals a share of max HP, so damage "
                 "never changed its yield, and it overlaps DEEPER PACT (+20%)."),
        "where": "scripts/entities/player.gd (choreo_fire_effects, 90 px status radius) · data/class_mods.gd",
    },
    {
        "severity": "caveat",
        "title": "Harness: the familiar needed its own policy",
        "body": ("The Spark summons on an RMB TAP. Mashing heavy (H) re-summons every cast, and a resummon "
                 "disperses the familiar before it reaches its prey: 600 taps, zero damage in 20 s. The "
                 "Spark's calibration grid adds LS (mash light, re-summon from neutral when no familiar is "
                 "alive) and two Fireball holds (0.4 s and a full 1.8 s), so the familiar picks and the "
                 "charge curve can be credited at all."),
        "where": "tools/sim/sim_pilot.gd (LS) · tools/sim/sim_stages.py (KIT_ROTATIONS)",
        "kit": "The Spark",
    },
]


def load(name: str):
    p = STAGES / f"{name}.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def fin(x):
    return None if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))) else x


## ── Multiple comparisons ─────────────────────────────────────────────────────
## A table family (all picks of all kits, or all mod singles, or all loadouts) runs hundreds of
## per-arena tests; at a plain 95% about 1 in 40 true nulls comes out "significant". Verdicts are
## therefore Benjamini-Hochberg adjusted at a 10% false-discovery rate within each family: of the
## results coloured up/down, at most ~10% are expected to be flukes. The raw 95% interval is still
## drawn. Assigned in place as v["verdict"]; the unadjusted one is kept as v["verdict95"].
FDR_Q = 0.10


def _p_two_sided(z: float) -> float:
    return math.erfc(abs(z) / math.sqrt(2.0))


def apply_bh(compares: list[dict]) -> None:
    tests = []
    for c in compares:
        for a, v in c["arenas"].items():
            v["verdict95"] = v["verdict"]
            l, se = v.get("log"), v.get("se")
            if l is None or se is None or (isinstance(l, float) and math.isnan(l)) \
                    or (isinstance(se, float) and (math.isnan(se) or se <= 0)):
                v["verdict"] = "flat"
                continue
            tests.append((_p_two_sided(l / se), v, l))
    tests.sort(key=lambda t: t[0])
    m = len(tests)
    cut = 0
    for i, (p, _, _) in enumerate(tests, 1):
        if p <= i / m * FDR_Q:
            cut = i
    for i, (p, v, l) in enumerate(tests, 1):
        v["verdict"] = ("up" if l > 0 else "down") if i <= cut else "flat"
        v["q_rank"] = i


def slim_compare(c: dict, sh: dict | None = None, raw: bool = False) -> dict:
    """Per-arena RAW ratios + intervals (what the CI cells draw), and composite offense/defense
    from the empirical-Bayes SHRUNK estimates when the stage computed them (what the tables rank
    by — see eb_priors in sim_stages.py). Raw composites ride along for the tooltip."""
    ## raw=True for a whole-build total: the shrinkage prior was fitted to SINGLE picks, and
    ## applying it to an 8-pick build would pull a genuinely large cumulative gain toward zero.
    sh = None if raw else (sh or c.get("shrunk"))
    return {
        "arenas": {a: {k: fin(v[k]) for k in ("ratio", "lo", "hi")}
                      | {"verdict": v["verdict"], "verdict95": v.get("verdict95", v["verdict"])}
                   for a, v in c["arenas"].items()},
        "offense": fin((sh or c)["offense"]), "defense": fin((sh or c)["defense"]),
        "offense_raw": fin(c["offense"]), "defense_raw": fin(c["defense"]),
    }


def slim_summary(s: dict) -> dict:
    return {a: {"value": fin(v["value"]), "policy": v.get("policy"),
                "n": len(v.get("vals", []))} for a, v in s.items() if a in ARENAS}


def nice(name: str) -> str:
    """Evolution and character names are authored in capitals for the pixel-font UI cards; the
    report sets them in title case so a table of mixed picks reads evenly."""
    return name.title() if name.isupper() else name


def top_abilities(by: dict, n: int = 6) -> list:
    tot = sum(by.values()) or 1.0
    rows = sorted(by.items(), key=lambda kv: -kv[1])[:n]
    return [{"id": k, "share": v / tot} for k, v in rows]


def main():
    out_path = HERE / "out" / "report.html"
    only_kits: list[str] | None = None
    for a in sys.argv[1:]:
        if a.startswith("--out="):
            out_path = Path(a.split("=", 1)[1])
        elif a.startswith("--kits="):   # preview a subset, e.g. --kits="The Drifter,The Demon"
            only_kits = [x.strip() for x in a.split("=", 1)[1].split(",")]

    cat = load("catalog")
    cal = load("calibrate")
    base = load("baseline")
    picks = load("picks")
    mods = load("mods")
    greedy = load("greedy")
    if cat is None or cal is None:
        raise SystemExit("run at least `catalog` and `calibrate` first")

    if picks:
        apply_bh([r["compare"] for k in picks["kits"].values() for r in k["picks"]])
    if mods:
        apply_bh([r["compare"] for k in mods["kits"].values() for r in k["singles"]])
        apply_bh([r["compare"] for k in mods["kits"].values() for r in k["loadouts"]])

    kits = []
    names_up: dict = {}
    for ch in cat["characters"]:
        cid = ch["id"]
        if cid not in cal["kits"] or (only_kits and cid not in only_kits):
            continue
        info = ch.get("info", {})
        for u in ch["ability_upgrades"]:
            names_up[u["id"]] = u["name"]
        disp = str(info.get("display_name", cid))
        ## Display names are authored upper-case for the pixel font; the report reads better in
        ## title case, and keeps the data id alongside because the two have drifted apart
        ## (the Drifter shows in game as the Sellsword).
        k = {"id": cid, "name": disp.title() if disp.isupper() else disp, "class": info.get("char_class", ""),
             "kit": ch["kit"], "weapon": info.get("starting_weapon", ""),
             "passive": info.get("passive_name", ""), "hp": info.get("base_hp"),
             "move": info.get("base_move_speed")}
        # Policies found by calibration, with the kit's damage split under each.
        k["policies"] = {}
        for a in ARENAS:
            rows = cal["kits"][cid].get(a, [])
            if rows:
                best = rows[0]
                k["policies"][a] = {
                    "key": best["key"], "value": best["mean"],
                    "runners_up": [{"key": r["key"], "value": r["mean"]} for r in rows[1:4]],
                    "abilities": top_abilities(best.get("by_ability", {})),
                    "warnings": best.get("warnings", []),
                }
        if base and cid in base["kits"]:
            b = base["kits"][cid]
            k["baseline"] = {a: {"value": fin(b[a]["value"]), "policy": b[a]["policy"],
                                 "vals": b[a]["vals"], "dtps": b[a].get("dtps"),
                                 "stats": b[a].get("stats", {})} for a in b}
        if picks and cid in picks["kits"]:
            rows = []
            for r in picks["kits"][cid]["picks"]:
                desc = r["description"]
                if r["id"] in PROC_CHAIN_PICKS:
                    desc += " · value inflated by the proc-chain bug (see findings)"
                rows.append({"id": r["id"], "name": nice(r["name"]), "kind": r["kind"], "role": r["role"],
                             "description": desc, "prereq": r["prereq"],
                             "max_rank": r.get("max_rank", 1), "applied_ok": r["applied_ok"],
                             "compare": slim_compare(r["compare"], r.get("shrunk")),
                             "policies": {a: v.get("policy") for a, v in r["summary"].items() if a in ARENAS}})
            k["picks"] = rows
        if mods and cid in mods["kits"]:
            m = mods["kits"][cid]
            mod_names = {x["id"]: nice(x["name"]) for x in ch["mods"]}
            mod_rarity = {x["id"]: x["rarity"] for x in ch["mods"]}
            mod_desc = {x["id"]: x["description"] for x in ch["mods"]}
            k["mods"] = {
                "singles": [{"id": r["mod"], "name": mod_names.get(r["mod"], r["mod"]),
                             "rarity": mod_rarity.get(r["mod"], ""), "description": mod_desc.get(r["mod"], ""),
                             "active_ok": r["active_ok"], "compare": slim_compare(r["compare"], r.get("shrunk"))}
                            for r in m["singles"]],
                "loadouts": [{"mods": r["mods"], "names": [mod_names.get(x, x) for x in r["mods"]],
                              "evolutions": r["evolutions"], "active_ok": r["active_ok"],
                              "compare": slim_compare(r["compare"], r.get("shrunk"))} for r in m["loadouts"]],
                "evolutions": [e | {"name": nice(e["name"])} for e in ch["mod_evolutions"]],
            }
        if mods and cid in mods["kits"]:
            k["mod_network"] = mod_network(mods["kits"][cid], ch)
        if picks and cid in picks["kits"]:
            k["dep_graph"] = dep_graph(picks["kits"][cid], ch, cat)
        if greedy and cid in greedy["kits"]:
            g = greedy["kits"][cid]
            k["greedy"] = {
                "build": g["build"],
                "steps": [{"step": s["step"], "pick": s["pick"], "stopped": s.get("stopped"),
                           "gain": slim_compare(s["gain"]) if s.get("gain") else None,
                           "cumulative": slim_compare(s["cumulative"], raw=True) if s.get("cumulative") else None,
                           "crashed": [{"pick": c["pick"], "cause": c.get("cause", ""), "error": c.get("error", "")}
                                       for c in s.get("crashed", [])],
                           "considered": [{"pick": c["pick"], "gain": slim_compare(c["gain"])}
                                          for c in s.get("considered", [])]} for s in g["steps"]],
                "final": slim_summary(g["final"]), "base": slim_summary(g["base"]),
            }
        kits.append(k)

    pool_names = {p["id"]: p["name"] for p in cat["pool"]} | {e["id"]: nice(e["name"]) for e in cat["evolutions"]}
    names = pool_names | names_up

    interim = None
    for a in sys.argv[1:]:
        if a.startswith("--interim="):
            interim = a.split("=", 1)[1]
        if a.startswith("--stages=") and "interim" in a:
            PROC_CHAIN_PICKS.update({"static_discharge", "lightning_reflexes"})
    data = {
        "interim": interim,
        "generated": date.today().isoformat(),
        "fingerprint": cal.get("_fp", ""),
        "stages": {n: (load(n) is not None) for n in ("calibrate", "baseline", "picks", "mods", "greedy")},
        "kits": kits,
        "names": names,
        "findings": sorted(MANUAL_FINDINGS + derive_findings(kits, names),
                           key=lambda f: SEV_ORDER.get(f["severity"], 9)),
        "counts": count_scenarios(),
    }
    html = TEMPLATE.read_text(encoding="utf-8")
    blob = json.dumps(data, separators=(",", ":")).replace("</", "<\\/")
    html = html.replace("/*__REPORT_DATA__*/null", blob)
    out_path.write_text(html, encoding="utf-8")
    print(f"wrote {out_path} ({out_path.stat().st_size / 1024:.0f} KB, {len(kits)} kits)")


def count_scenarios() -> int:
    cache = HERE / "out" / "cache"
    return sum(1 for _ in cache.rglob("*.json")) if cache.exists() else 0


# ─── rule-derived findings ────────────────────────────────────────────────────

def derive_findings(kits: list, names: dict) -> list:
    out = []

    # 1. Harness/data integrity — a pick or mod that did not land is a content bug, not balance.
    for k in kits:
        for p in k.get("picks", []):
            if not p["applied_ok"]:
                out.append({"severity": "bug", "title": f"{k['name']}: pick '{p['name']}' was not applied",
                            "body": "UpgradeManager could not resolve this id for the kit — it cannot be offered correctly.",
                            "kit": k["id"]})
        for m in k.get("mods", {}).get("singles", []):
            if not m["active_ok"]:
                out.append({"severity": "bug", "title": f"{k['name']}: mod '{m['name']}' is not active on its own kit",
                            "body": "ProgressionManager.get_active_class_mods dropped it; the mod would do nothing when equipped.",
                            "kit": k["id"]})

    # 2. Picks that do nothing for damage, with intervals tight enough to say so. "Not
    #    significant" alone is not evidence of no effect — a wide interval is just unresolved — so
    #    the claim is an equivalence test: every offence arena's 95% interval inside ±EQUIV.
    #    Defensive picks (survive / space roles) are expected to leave damage alone and are only
    #    listed if survival was resolved as well.
    for k in kits:
        dead, unresolved_def = [], []
        for p in k.get("picks", []):
            A = p["compare"]["arenas"]
            off = [A[a] for a in ("single", "cluster", "horde") if a in A]
            if not off or not all(v["lo"] and v["hi"] and v["lo"] >= 1 - EQUIV and v["hi"] <= 1 + EQUIV
                                  for v in off):
                continue
            defensive = p.get("role") in ("survive", "space")
            pr = A.get("pressure")
            pres_tight = pr and pr["lo"] and pr["hi"] and pr["lo"] >= 1 - EQUIV and pr["hi"] <= 1 + EQUIV
            if not defensive:
                dead.append(p)
            elif pres_tight:
                dead.append(p)
            elif pr and pr["verdict"] == "flat":
                unresolved_def.append(p)
        if dead:
            out.append({"severity": "warn", "kit": k["id"],
                        "title": f"{k['name']}: {len(dead)} pick(s) that do nothing measurable for damage or clear speed",
                        "body": ", ".join(p["name"] for p in dead) + f". Every offence interval sits inside "
                                f"±{EQUIV * 100:.0f}%. For a damage or kit pick this usually means it is not "
                                "working for this kit (or only works in a situation none of the arenas create).",
                        "items": [p["id"] for p in dead]})
        if unresolved_def:
            out.append({"severity": "caveat", "kit": k["id"],
                        "title": f"{k['name']}: {len(unresolved_def)} defensive pick(s) the survival test could not resolve",
                        "body": ", ".join(p["name"] for p in unresolved_def) + ". No offence effect (expected), "
                                "and the survival interval is too wide to call. Their value is unmeasured, not zero.",
                        "items": [p["id"] for p in unresolved_def]})

    # 3. Trap picks: a pick that costs the kit at least 3% overall (shrunk estimate) with at least
    #    one arena measurably down and none measurably up. A statistically real -1% is not worth
    #    a line in a report; the threshold is practical significance, not a p-value.
    for k in kits:
        bad = [p for p in k.get("picks", [])
               if (weighted_mid(p["compare"]) or 1.0) <= 0.97
               and any(v["verdict"] == "down" for v in p["compare"]["arenas"].values())
               and not any(v["verdict"] == "up" for v in p["compare"]["arenas"].values())]
        for p in bad:
            downs = [f"{ARENA_LABEL[a]} {pct(v['ratio'])}" for a, v in p["compare"]["arenas"].items()
                     if v["verdict"] == "down"]
            out.append({"severity": "warn", "kit": k["id"],
                        "title": f"{k['name']}: '{p['name']}' is a trap pick",
                        "body": f"Measurably worse in {', '.join(downs)} and better nowhere (95% interval).",
                        "items": [p["id"]]})

    # 4. Roster outliers at level 1 — a kit far off the roster median in any arena.
    for a in ARENAS:
        vals = [(k, k["baseline"][a]["value"]) for k in kits if "baseline" in k and a in k["baseline"]
                and k["baseline"][a]["value"] is not None]
        if len(vals) < 4:
            continue
        med = sorted(v for _, v in vals)[len(vals) // 2]
        for k, v in vals:
            if med > 0 and (v / med >= 1.6 or v / med <= 0.55):
                out.append({"severity": "info", "kit": k["id"],
                            "title": f"{k['name']}: {v / med:.2f}× the roster median in {ARENA_LABEL[a]}",
                            "body": f"{fmt_val(a, v)} against a median of {fmt_val(a, med)} at level 1, no mods."})

    # 5. Class mods that do nothing on their own (equivalence, as in rule 2, over all four arenas;
    #    a mod that only matters as an evolution ingredient is still worth knowing about).
    for k in kits:
        inert = []
        for m in k.get("mods", {}).get("singles", []):
            A = m["compare"]["arenas"]
            if A and all(v["lo"] and v["hi"] and v["lo"] >= 1 - EQUIV and v["hi"] <= 1 + EQUIV
                         for a, v in A.items() if a != "pressure") \
                    and A.get("pressure", {}).get("verdict", "flat") == "flat":
                inert.append(m)
        if inert:
            out.append({"severity": "warn", "kit": k["id"],
                        "title": f"{k['name']}: {len(inert)} class mod(s) with no measurable effect alone",
                        "body": ", ".join(m["name"] for m in inert) + f". Offence within ±{EQUIV * 100:.0f}% "
                                "in every arena and survival unchanged. Check whether they need a condition "
                                "no arena creates, or only matter as an evolution ingredient.",
                        "items": [m["id"] for m in inert]})

    # 5b. Builds that crashed or hung the engine during the build search.
    for k in kits:
        for st_ in (k.get("greedy") or {}).get("steps", []):
            for c in st_.get("crashed", []):
                out.append({"severity": "bug", "kit": k["id"],
                            "title": f"{k['name']}: build crashed the engine at level {st_['step'] + 1} (candidate '{c['pick']}')",
                            "body": f"{c.get('cause', '')}. {c.get('error', '')[:400]}",
                            "items": [c["pick"]]})

    # 6. Bot-coverage caveats: a requested skill the bot never landed.
    for k in kits:
        for a, pol in k.get("policies", {}).items():
            for w in pol.get("warnings", []):
                out.append({"severity": "caveat", "kit": k["id"],
                            "title": f"{k['name']} ({ARENA_LABEL[a]}): {w}",
                            "body": "The winning policy asked for this but it never happened; that arena's number understates the kit."})
    order = {"bug": 0, "decision": 1, "fixed": 2, "warn": 3, "info": 4, "caveat": 5}
    out.sort(key=lambda f: order.get(f["severity"], 9))
    return out


## Equivalence margin for "does nothing": an effect is called absent only when the whole 95%
## interval sits within this band around zero change.
EQUIV = 0.05


def weighted_mid(c: dict):
    off, de = c.get("offense"), c.get("defense")
    if off and de:
        return math.sqrt(off * de)
    return off or de


def pct(r) -> str:
    return "-" if r is None else f"{(r - 1) * 100:+.0f}%"


ARENA_LABEL = {"single": "single-target DPS", "cluster": "pack DPS", "horde": "clear speed",
               "pressure": "survival"}


def fmt_val(a: str, v: float) -> str:
    if a == "pressure":
        return f"{v:.0f}s"
    if a == "horde":
        return f"{v:.0f} kills/min"
    return f"{v:.0f} DPS"


if __name__ == "__main__":
    main()
