class_name CryptEnemyData
extends RefCounted
## Level 2 — The Catacombs — enemy definitions (Minifantasy_Undead_Creatures pack).
##
## Twelve rank-and-file roles; the miniboss and final boss live in their own factories
## (SkeletonMinotaurData / ZombieGiantData) because bosses carry choreographed skills.
##
##   crypt_fodder        Headless Skeleton          — fragile melee swarm
##   crypt_swarmer       Jumping Skull              — fastest unit, paper-thin
##   crypt_skirmisher    Reanimated Skeleton Warrior— standard melee
##   crypt_raider        Reanimated Zombie Warrior  — slower, meatier melee
##   crypt_archer        Reanimated Skeleton Archer — ranged, arrow
##   crypt_zombie_archer Reanimated Zombie Archer   — tougher ranged, heavier arrow
##   crypt_caster        Reanimated Skeleton Mage   — ranged, spell bolt
##   crypt_zombie_caster Reanimated Zombie Mage     — tougher caster, curse bolt
##   crypt_ghost         Ghost                      — fast harasser, ignores armour
##   crypt_brute         Zombie Bear                — heavy
##   crypt_heavy         Zombie Minotaur            — heaviest rank-and-file
##   crypt_cavalry       Skeletal Horse + Rider     — fast charger
##
## Scenes are generated by tools/gen_undead_scenes.gd. Registered in EnemyRegistry.
##
## Scaling intent: The Catacombs is biome 2, so the line troops sit roughly 1.5-2x the
## equivalent cave role. Cave reference: fodder 8hp/6dmg, swarmer 12/6, brute 90/20/8armor.

const COL_BONE: Color  = Color(0.86, 0.84, 0.74, 1.0)
const COL_ROT: Color   = Color(0.55, 0.68, 0.45, 1.0)
const COL_SPECT: Color = Color(0.60, 0.85, 0.95, 1.0)


# ── Melee line ────────────────────────────────────────────────────────────────

static func create_crypt_fodder() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_fodder"
	def.enemy_name     = "Headless Skeleton"
	def.tags           = ["Melee", "Common", "Swarm", "Undead"]
	def.base_stats     = {"max_hp": 14.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 78.0
	def.contact_damage = 8.0
	def.base_armor     = 0.0
	def.xp_value       = 0.6
	def.health_drop_chance   = 0.04
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.25   ## loose bones — scatters easily
	return def


static func create_crypt_swarmer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_swarmer"
	def.enemy_name     = "Jumping Skull"
	def.tags           = ["Melee", "Common", "Swarm", "Undead"]
	def.base_stats     = {"max_hp": 9.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 138.0        ## the biome's fastest — the cave bat's role
	def.contact_damage = 6.0
	def.base_armor     = 0.0
	def.xp_value       = 0.5
	def.health_drop_chance   = 0.03
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.6
	def.sprite_scale         = Vector2(0.85, 0.85)
	return def


static func create_crypt_skirmisher() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_skirmisher"
	def.enemy_name     = "Reanimated Skeleton"
	def.tags           = ["Melee", "Common", "Undead"]
	def.base_stats     = {"max_hp": 22.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 95.0
	def.contact_damage = 10.0
	def.base_armor     = 2.0
	def.xp_value       = 1.2
	def.health_drop_chance   = 0.06
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.0
	return def


static func create_crypt_raider() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_raider"
	def.enemy_name     = "Reanimated Zombie"
	def.tags           = ["Melee", "Common", "Undead"]
	def.base_stats     = {"max_hp": 38.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 62.0
	def.contact_damage = 14.0
	def.base_armor     = 3.0
	def.xp_value       = 2.0
	def.health_drop_chance   = 0.08
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.75
	return def


static func create_crypt_ghost() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_ghost"
	def.enemy_name     = "Ghost"
	def.tags           = ["Melee", "Aerial", "Undead"]
	def.base_stats     = {"max_hp": 16.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 122.0
	def.contact_damage = 11.0
	def.base_armor     = 0.0
	def.xp_value       = 1.5
	def.health_drop_chance   = 0.05
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.4
	def.base_modulate        = Color(1.0, 1.0, 1.0, 0.80)   ## reads as incorporeal
	return def


static func create_crypt_brute() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_brute"
	def.enemy_name     = "Zombie Bear"
	def.tags           = ["Melee", "Tank", "Undead"]
	def.base_stats     = {"max_hp": 120.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 46.0
	def.contact_damage = 24.0
	def.base_armor     = 9.0
	def.xp_value       = 6.0
	def.health_drop_chance   = 0.20
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.25
	def.sprite_scale         = Vector2(1.25, 1.25)
	return def


static func create_crypt_heavy() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_heavy"
	def.enemy_name     = "Zombie Minotaur"
	def.tags           = ["Melee", "Tank", "Undead"]
	def.base_stats     = {"max_hp": 165.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 40.0
	def.contact_damage = 30.0
	def.base_armor     = 12.0
	def.xp_value       = 8.0
	def.health_drop_chance   = 0.24
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.15
	def.sprite_scale         = Vector2(1.35, 1.35)
	return def


static func create_crypt_cavalry() -> EnemyDefinition:
	## Skeletal Horse with its rider composited on (assets/generated/skeletal_rider).
	## Fast and heavy — the unit that punishes standing still in an open crypt hall.
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_cavalry"
	def.enemy_name     = "Bone Rider"
	def.tags           = ["Melee", "Undead"]
	def.base_stats     = {"max_hp": 70.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 128.0
	def.contact_damage = 18.0
	def.base_armor     = 4.0
	def.xp_value       = 4.0
	def.health_drop_chance   = 0.14
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.5
	def.sprite_scale         = Vector2(1.2, 1.2)
	return def


# ── Ranged line ───────────────────────────────────────────────────────────────

static func create_crypt_archer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_archer"
	def.enemy_name     = "Skeleton Archer"
	def.tags           = ["Ranged", "Common", "Undead"]
	def.base_stats     = {"max_hp": 18.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 55.0
	def.contact_damage = 5.0
	def.base_armor     = 1.0
	def.xp_value       = 1.6
	def.health_drop_chance   = 0.06
	def.behavior_type        = "ranged"
	def.preferred_range      = 170.0
	def.auto_attack = _arrow_attack(
		"crypt_arrow",
		"res://assets/minifantasy/Minifantasy_Undead_Creatures_v1.0/Minifantasy_Undead_Creatures_Assets/Reanimated_Skeleton_Archer/Attack_Projectile.png",
		9.0, 165.0, 170.0, 2.0)
	return def


static func create_crypt_zombie_archer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_zombie_archer"
	def.enemy_name     = "Zombie Archer"
	def.tags           = ["Ranged", "Undead"]
	def.base_stats     = {"max_hp": 28.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 45.0
	def.contact_damage = 6.0
	def.base_armor     = 2.0
	def.xp_value       = 2.2
	def.health_drop_chance   = 0.08
	def.behavior_type        = "ranged"
	def.preferred_range      = 185.0
	def.auto_attack = _arrow_attack(
		"crypt_rot_arrow",
		"res://assets/minifantasy/Minifantasy_Undead_Creatures_v1.0/Minifantasy_Undead_Creatures_Assets/Reanimated_Zombie_Archer/Attack_Projectile.png",
		14.0, 150.0, 185.0, 2.6)
	return def


static func create_crypt_caster() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_caster"
	def.enemy_name     = "Skeleton Mage"
	def.tags           = ["Ranged", "Caster", "Undead"]
	def.base_stats     = {"max_hp": 20.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 50.0
	def.contact_damage = 5.0
	def.base_armor     = 0.0
	def.xp_value       = 2.0
	def.health_drop_chance   = 0.07
	def.behavior_type        = "ranged"
	def.preferred_range      = 175.0
	def.auto_attack = _spell_attack(
		"crypt_bone_bolt",
		"res://assets/minifantasy/Minifantasy_Undead_Creatures_v1.0/Minifantasy_Undead_Creatures_Assets/Reanimated_Skeleton_Mage/Casted_Spell.png",
		12, 12.0, "Void", 130.0, 175.0, 2.4)
	return def


static func create_crypt_zombie_caster() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "crypt_zombie_caster"
	def.enemy_name     = "Zombie Mage"
	def.tags           = ["Ranged", "Caster", "Undead"]
	def.base_stats     = {"max_hp": 32.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 42.0
	def.contact_damage = 6.0
	def.base_armor     = 1.0
	def.xp_value       = 2.6
	def.health_drop_chance   = 0.09
	def.behavior_type        = "ranged"
	def.preferred_range      = 190.0
	def.auto_attack = _spell_attack(
		"crypt_plague_bolt",
		"res://assets/minifantasy/Minifantasy_Undead_Creatures_v1.0/Minifantasy_Undead_Creatures_Assets/Reanimated_Zombie_Mage/Casted_Spell.png",
		12, 17.0, "Poison", 120.0, 190.0, 3.0)
	return def


# ── Projectile builders ───────────────────────────────────────────────────────

## The archers' Attack_Projectile.png sheets are 96x96 — the pack's standard 3x3 grid of
## eight facings around an empty centre, the same shape ChainFactory reads for every other
## single-frame directional projectile. Reusing its helper keeps one cell mapping in the
## codebase instead of two.
static func _arrow_attack(id: String, sheet: String, damage: float, speed: float,
		range_px: float, cooldown: float) -> AbilityDefinition:
	var config := ProjectileConfig.new()
	config.motion_type = "directional"
	config.speed = speed
	config.max_range = range_px * 1.4
	config.hit_radius = 6.0
	config.sprite_frames = ChainFactory._grid8_frames(sheet, "undead_" + id)
	config.use_directional_anims = true
	config.fallback_color = Color(0.86, 0.84, 0.74, 1.0)
	config.pierce_count = 0

	var dmg := DealDamageEffect.new()
	dmg.damage_type = "Physical"
	dmg.base_damage = damage
	config.on_hit_effects = [dmg]

	var tags: Array[String] = ["Ranged", "Projectile"]
	return _ability_from(id, config, range_px, cooldown, tags)


## The mages' Casted_Spell.png sheets are a single 12-frame row — an animated, directionless
## bolt. use_directional_anims stays false and `animation` is set so the manager plays the
## loop and rotates it toward travel, rather than freezing it on frame 0.
static func _spell_attack(id: String, sheet: String, frame_count: int, damage: float,
		damage_type: String, speed: float, range_px: float, cooldown: float) -> AbilityDefinition:
	var config := ProjectileConfig.new()
	config.motion_type = "directional"
	config.speed = speed
	config.max_range = range_px * 1.4
	config.hit_radius = 8.0
	config.sprite_frames = _row_frames(sheet, frame_count, 14.0)
	config.use_directional_anims = false
	config.animation = "default"
	config.fallback_color = Color(0.55, 0.35, 0.85, 1.0)
	config.pierce_count = 0

	var dmg := DealDamageEffect.new()
	dmg.damage_type = damage_type
	dmg.base_damage = damage
	config.on_hit_effects = [dmg]

	var tags: Array[String] = ["Ranged", "Projectile", "Caster"]
	return _ability_from(id, config, range_px, cooldown, tags)


static func _row_frames(path: String, count: int, fps: float) -> SpriteFrames:
	var tex: Texture2D = load(path)
	var frames := SpriteFrames.new()
	## clear_all() KEEPS (re-creates) an empty "default" animation, so adding it again fails and
	## pushes an engine error every time the crypt casters are built — two per registry build.
	## Reuse the built-in one, same as weapon_factory.gd and chain_factory.gd already do.
	frames.clear_all()
	frames.set_animation_loop(&"default", true)
	frames.set_animation_speed(&"default", fps)
	if tex == null:
		return frames
	for i in count:
		var cell := AtlasTexture.new()
		cell.atlas = tex
		cell.region = Rect2(i * 32, 0, 32, 32)
		cell.filter_clip = true
		frames.add_frame(&"default", cell)
	return frames


## `tags` is Array[String], not Array: AbilityDefinition.tags is a TYPED array, and assigning an
## untyped one compiles cleanly and then throws at runtime ("Invalid assignment of property 'tags'
## with value of type 'Array'"). It only surfaced when EnemySpawnManager built the registry in a
## running game — every static check passed.
static func _ability_from(id: String, config: ProjectileConfig, range_px: float,
		cooldown: float, tags: Array[String]) -> AbilityDefinition:
	var spawn := SpawnProjectilesEffect.new()
	spawn.projectile = config
	spawn.spawn_pattern = "aimed_single"
	spawn.count = 1

	var aa := AbilityDefinition.new()
	aa.ability_id = id
	aa.ability_name = id
	aa.tags = tags
	aa.cooldown_base = cooldown
	aa.mode = "Auto"
	var targeting := TargetingRule.new()
	targeting.type = "nearest_enemy"
	targeting.max_range = range_px * 1.3
	aa.targeting = targeting
	aa.effects = [spawn]
	return aa
