class_name EnemyRegistry
extends RefCounted
## Central registry for all enemy definitions. Built once, cached.

static var _definitions: Dictionary = {}
static var _built: bool = false


static func build_all() -> void:
	if _built:
		return
	_built = true
	_definitions["fodder"] = FodderData.create()
	_definitions["swarmer"] = SwarmerData.create()
	_definitions["brute"] = BruteData.create()
	_definitions["carrier"] = CarrierData.create()
	_definitions["stalker"] = StalkerData.create()
	_definitions["caster"] = CasterData.create()
	_definitions["guardian"] = GuardianData.create()
	_definitions["herald"] = HeraldData.create()
	## Phase 3 miniboss
	_definitions["warped_colossus"] = WarpedColossusData.create()
	## Phase 5 final boss
	_definitions["heart_of_the_deep"] = HeartOfTheDeepData.create()
	## Phase 5 Phase-Warped variants
	_definitions["warped_fodder"] = WarpedEnemyData.create_warped_fodder()
	_definitions["warped_swarmer"] = WarpedEnemyData.create_warped_swarmer()
	_definitions["warped_brute"] = WarpedEnemyData.create_warped_brute()
	_definitions["warped_caster"] = WarpedEnemyData.create_warped_caster()
	## ── Level 1 — The Cave ───────────────────────────────────────────────────
	## Cave bosses (replace the tinted Colossus/Heart via LevelData boss ids)
	_definitions["ancient_troll"] = AncientTrollData.create()
	_definitions["goblin_king"]   = GoblinKingData.create()
	_definitions["cave_fodder"]     = CaveEnemyData.create_cave_fodder()
	_definitions["cave_swarmer"]    = CaveEnemyData.create_cave_swarmer()
	_definitions["cave_brute"]      = CaveEnemyData.create_cave_brute()
	_definitions["cave_bat"]        = CaveEnemyData.create_cave_bat()
	_definitions["cave_raider"]     = CaveEnemyData.create_cave_raider()
	_definitions["cave_skirmisher"] = CaveEnemyData.create_cave_skirmisher()
	## ── Level 2 — The Catacombs ──────────────────────────────────────────────
	## Minifantasy_Undead_Creatures pack; scenes generated by tools/gen_undead_scenes.gd.
	_definitions["skeleton_minotaur"]   = SkeletonMinotaurData.create()   ## miniboss
	_definitions["zombie_giant"]        = ZombieGiantData.create()        ## final boss
	_definitions["crypt_fodder"]        = CryptEnemyData.create_crypt_fodder()
	_definitions["crypt_swarmer"]       = CryptEnemyData.create_crypt_swarmer()
	_definitions["crypt_skirmisher"]    = CryptEnemyData.create_crypt_skirmisher()
	_definitions["crypt_raider"]        = CryptEnemyData.create_crypt_raider()
	_definitions["crypt_ghost"]         = CryptEnemyData.create_crypt_ghost()
	_definitions["crypt_brute"]         = CryptEnemyData.create_crypt_brute()
	_definitions["crypt_heavy"]         = CryptEnemyData.create_crypt_heavy()
	_definitions["crypt_cavalry"]       = CryptEnemyData.create_crypt_cavalry()
	_definitions["crypt_archer"]        = CryptEnemyData.create_crypt_archer()
	_definitions["crypt_zombie_archer"] = CryptEnemyData.create_crypt_zombie_archer()
	_definitions["crypt_caster"]        = CryptEnemyData.create_crypt_caster()
	_definitions["crypt_zombie_caster"] = CryptEnemyData.create_crypt_zombie_caster()
	## ── Level 3 — The Nightmare Realm ────────────────────────────────────────
	## Minifantasy_Monster_Creatures pack; scenes generated by tools/gen_nightmare_scenes.gd.
	_definitions["centaur_king"]   = CentaurKingData.create()     ## miniboss
	_definitions["angel_of_death"] = AngelOfDeathData.create()    ## final boss
	_definitions["nm_fodder"]      = NightmareEnemyData.create_nm_fodder()
	_definitions["nm_swarmer"]     = NightmareEnemyData.create_nm_swarmer()
	_definitions["nm_skirmisher"]  = NightmareEnemyData.create_nm_skirmisher()
	_definitions["nm_stalker"]     = NightmareEnemyData.create_nm_stalker()
	_definitions["nm_raider"]      = NightmareEnemyData.create_nm_raider()
	_definitions["nm_ambusher"]    = NightmareEnemyData.create_nm_ambusher()
	_definitions["nm_lurker"]      = NightmareEnemyData.create_nm_lurker()
	_definitions["nm_aerial"]      = NightmareEnemyData.create_nm_aerial()
	_definitions["nm_archer"]      = NightmareEnemyData.create_nm_archer()
	_definitions["nm_caster"]      = NightmareEnemyData.create_nm_caster()
	_definitions["nm_royal"]       = NightmareEnemyData.create_nm_royal()
	_definitions["nm_spore"]       = NightmareEnemyData.create_nm_spore()
	_definitions["nm_brute"]       = NightmareEnemyData.create_nm_brute()
	_definitions["nm_heavy"]       = NightmareEnemyData.create_nm_heavy()


static func get_def(enemy_id: String) -> EnemyDefinition:
	build_all()
	return _definitions.get(enemy_id)


static func get_all() -> Dictionary:
	build_all()
	return _definitions
