class_name EnemyRegistry
extends RefCounted
## Central registry for all enemy definitions. Built once, cached.

static var _definitions: Dictionary = {}
static var _built: bool = false


static func build_all() -> void:
	if _built:
		return
	_built = true
	_definitions["fodder"] = FodderData.create()
	_definitions["swarmer"] = SwarmerData.create()
	_definitions["brute"] = BruteData.create()
	_definitions["carrier"] = CarrierData.create()
	_definitions["stalker"] = StalkerData.create()
	_definitions["caster"] = CasterData.create()
	_definitions["guardian"] = GuardianData.create()
	_definitions["herald"] = HeraldData.create()
	## Phase 3 miniboss
	_definitions["warped_colossus"] = WarpedColossusData.create()
	## Phase 5 final boss
	_definitions["heart_of_the_deep"] = HeartOfTheDeepData.create()
	## Phase 5 Phase-Warped variants
	_definitions["warped_fodder"] = WarpedEnemyData.create_warped_fodder()
	_definitions["warped_swarmer"] = WarpedEnemyData.create_warped_swarmer()
	_definitions["warped_brute"] = WarpedEnemyData.create_warped_brute()
	_definitions["warped_caster"] = WarpedEnemyData.create_warped_caster()
	## ── Level 1 — The Cave ───────────────────────────────────────────────────
	## Cave bosses (replace the tinted Colossus/Heart via LevelData boss ids)
	_definitions["ancient_troll"] = AncientTrollData.create()
	_definitions["goblin_king"]   = GoblinKingData.create()
	_definitions["cave_fodder"]     = CaveEnemyData.create_cave_fodder()
	_definitions["cave_swarmer"]    = CaveEnemyData.create_cave_swarmer()
	_definitions["cave_brute"]      = CaveEnemyData.create_cave_brute()
	_definitions["cave_bat"]        = CaveEnemyData.create_cave_bat()
	_definitions["cave_raider"]     = CaveEnemyData.create_cave_raider()
	_definitions["cave_skirmisher"] = CaveEnemyData.create_cave_skirmisher()
	## ── Level 2 — The Catacombs ──────────────────────────────────────────────
	## Minifantasy_Undead_Creatures pack; scenes generated by tools/gen_undead_scenes.gd.
	_definitions["skeleton_minotaur"]   = SkeletonMinotaurData.create()   ## miniboss
	_definitions["zombie_giant"]        = ZombieGiantData.create()        ## final boss
	_definitions["crypt_fodder"]        = CryptEnemyData.create_crypt_fodder()
	_definitions["crypt_swarmer"]       = CryptEnemyData.create_crypt_swarmer()
	_definitions["crypt_skirmisher"]    = CryptEnemyData.create_crypt_skirmisher()
	_definitions["crypt_raider"]        = CryptEnemyData.create_crypt_raider()
	_definitions["crypt_ghost"]         = CryptEnemyData.create_crypt_ghost()
	_definitions["crypt_brute"]         = CryptEnemyData.create_crypt_brute()
	_definitions["crypt_heavy"]         = CryptEnemyData.create_crypt_heavy()
	_definitions["crypt_cavalry"]       = CryptEnemyData.create_crypt_cavalry()
	_definitions["crypt_archer"]        = CryptEnemyData.create_crypt_archer()
	_definitions["crypt_zombie_archer"] = CryptEnemyData.create_crypt_zombie_archer()
	_definitions["crypt_caster"]        = CryptEnemyData.create_crypt_caster()
	_definitions["crypt_zombie_caster"] = CryptEnemyData.create_crypt_zombie_caster()
	## ── Level 3 — The Nightmare Realm ────────────────────────────────────────
	## Minifantasy_Monster_Creatures pack; scenes generated by tools/gen_nightmare_scenes.gd.
	_definitions["centaur_king"]   = CentaurKingData.create()     ## miniboss
	_definitions["angel_of_death"] = AngelOfDeathData.create()    ## final boss
	_definitions["nm_fodder"]      = NightmareEnemyData.create_nm_fodder()
	_definitions["nm_swarmer"]     = NightmareEnemyData.create_nm_swarmer()
	_definitions["nm_skirmisher"]  = NightmareEnemyData.create_nm_skirmisher()
	_definitions["nm_stalker"]     = NightmareEnemyData.create_nm_stalker()
	_definitions["nm_raider"]      = NightmareEnemyData.create_nm_raider()
	_definitions["nm_ambusher"]    = NightmareEnemyData.create_nm_ambusher()
	_definitions["nm_lurker"]      = NightmareEnemyData.create_nm_lurker()
	_definitions["nm_aerial"]      = NightmareEnemyData.create_nm_aerial()
	_definitions["nm_archer"]      = NightmareEnemyData.create_nm_archer()
	_definitions["nm_caster"]      = NightmareEnemyData.create_nm_caster()
	_definitions["nm_royal"]       = NightmareEnemyData.create_nm_royal()
	_definitions["nm_spore"]       = NightmareEnemyData.create_nm_spore()
	_definitions["nm_brute"]       = NightmareEnemyData.create_nm_brute()
	_definitions["nm_heavy"]       = NightmareEnemyData.create_nm_heavy()
	## ── Level 4 — The Threshold ──────────────────────────────────────────────
	## Two packs split by depth: Minifantasy_Dark_Brotherhood is the cult holding the
	## door (phases 1-3), Minifantasy_Dark_Orc_Army is what came through it (phases 4-5).
	## Scenes generated by tools/gen_threshold_scenes.gd.
	_definitions["ritual_guard"]   = RitualGuardData.create()     ## miniboss
	_definitions["pale_champion"]  = PaleChampionData.create()    ## final boss
	_definitions["th_fodder"]      = ThresholdEnemyData.create_th_fodder()
	_definitions["th_swarmer"]     = ThresholdEnemyData.create_th_swarmer()
	_definitions["th_zealot"]      = ThresholdEnemyData.create_th_zealot()
	_definitions["th_skirmisher"]  = ThresholdEnemyData.create_th_skirmisher()
	_definitions["th_sentinel"]    = ThresholdEnemyData.create_th_sentinel()
	_definitions["th_archer"]      = ThresholdEnemyData.create_th_archer()
	_definitions["th_caster"]      = ThresholdEnemyData.create_th_caster()
	_definitions["th_flagellant"]  = ThresholdEnemyData.create_th_flagellant()
	_definitions["th_possessed"]   = ThresholdEnemyData.create_th_possessed()
	_definitions["th_hound"]       = ThresholdEnemyData.create_th_hound()
	_definitions["th_abomination"] = ThresholdEnemyData.create_th_abomination()
	_definitions["th_raider"]      = ThresholdEnemyData.create_th_raider()
	_definitions["th_berserker"]   = ThresholdEnemyData.create_th_berserker()
	_definitions["th_phalanx"]     = ThresholdEnemyData.create_th_phalanx()
	_definitions["th_arbalist"]    = ThresholdEnemyData.create_th_arbalist()
	_definitions["th_warg"]        = ThresholdEnemyData.create_th_warg()
	_definitions["th_troll"]       = ThresholdEnemyData.create_th_troll()

	## Capture the shipped numbers, then stamp on whatever the Unit Editor has tuned.
	## Runs here so a tuned value is live from the first enemy the game spawns, with no
	## caller having to remember to ask for it.
	_snapshot()
	apply_balance_overrides()


static func get_def(enemy_id: String) -> EnemyDefinition:
	build_all()
	return _definitions.get(enemy_id)


static func get_all() -> Dictionary:
	build_all()
	return _definitions


## ── Balance-override layer ───────────────────────────────────────────────────
##
## This registry is the ONE place every enemy definition is created, so it is also the one
## place a tuned value has to reach — 24 factories, one seam. Definitions are built once
## and cached, and the entities that read them hold no copy of the numbers, so mutating
## the cached definition in place is what "apply" means here.
##
## `_pristine` is the shipped value of every tunable, captured BEFORE the first apply. It
## is what BalanceRegistry shows as the anchor, and what a revert restores — without it,
## re-applying after an edit would compound onto the already-tuned value and the shipped
## number would be gone for the rest of the session.
##
## Tunable properties are listed here rather than discovered, because EnemyDefinition also
## carries SpriteFrames, ability graphs and group arrays that are not balance.
const TUNABLE: Array[String] = [
	"contact_damage", "move_speed", "base_armor", "xp_value", "health_drop_chance",
	"aggro_range", "engage_distance", "preferred_range", "retarget_interval",
	"aa_interval_override", "knockback_multiplier",
]

static var _pristine: Dictionary = {}


static func _snapshot() -> void:
	if not _pristine.is_empty():
		return
	for eid: String in _definitions.keys():
		var def: EnemyDefinition = _definitions[eid]
		if def == null:
			continue
		var row: Dictionary = {}
		for prop: String in TUNABLE:
			row[prop] = def.get(prop)
		row["max_hp"] = float(def.base_stats.get("max_hp", 0.0))
		_pristine[eid] = row


## The shipped value of one field, or NAN when the enemy or field is unknown. NAN rather
## than 0.0 so BalanceRegistry can tell "this enemy has no such field" from "it is zero".
static func base_value(enemy_id: String, field: String) -> float:
	build_all()
	var row: Variant = _pristine.get(enemy_id, null)
	if not (row is Dictionary):
		return NAN
	var v: Variant = (row as Dictionary).get(field, null)
	if v is float or v is int:
		return float(v)
	return NAN


## Restore every definition to its shipped numbers, then stamp the active overrides on.
## Restore-then-apply (rather than apply-on-top) is what makes this safe to call repeatedly
## from the Unit Editor while tuning.
static func apply_balance_overrides() -> void:
	build_all()
	_snapshot()
	for eid: String in _definitions.keys():
		var def: EnemyDefinition = _definitions[eid]
		if def == null:
			continue
		var row: Dictionary = _pristine.get(eid, {})
		for prop: String in TUNABLE:
			if not row.has(prop):
				continue
			def.set(prop, BalanceOverrides.get_float(
					BalanceOverrides.enemy_path(eid, prop), float(row[prop])))
		if row.has("max_hp"):
			def.base_stats["max_hp"] = BalanceOverrides.get_float(
					BalanceOverrides.enemy_path(eid, "max_hp"), float(row["max_hp"]))
