class_name NightmareEnemyData
extends RefCounted
## Level 3 — The Nightmare Realm — enemy definitions (Minifantasy_Monster_Creatures pack).
##
## Thirteen rank-and-file roles; the miniboss and final boss live in their own factories
## (CentaurKingData / AngelOfDeathData) because bosses carry choreographed skills.
##
##   nm_fodder      Giant Rat              — fragile melee swarm
##   nm_swarmer     Dire Wolf              — fastest unit, paper-thin (Werewolf wolf shape)
##   nm_skirmisher  Gnoll                  — standard melee
##   nm_stalker     Cursed Wanderer        — humanoid melee (Werewolf human shape)
##   nm_raider      Deep One               — slower, meatier melee
##   nm_ambusher    Chest Mimic            — high burst, low mobility
##   nm_aerial      Gargoyle               — fast flying harasser
##   nm_archer      Ratfolk Slinger        — ranged, hurled refuse
##   nm_caster      Brain Slayer           — ranged, psychic bolt (Void)
##   nm_royal       Ratfolk Monarch        — elite ranged, thrown rat
##   nm_spore       Predatory Mushroom     — near-stationary zone turret (Poison)
##   nm_brute       Demon Spider           — heavy
##   nm_heavy       Giant                  — heaviest rank-and-file
##
## Scenes are generated by tools/gen_nightmare_scenes.gd. Registered in EnemyRegistry.
##
## Scaling intent: biome 3 sits roughly 1.5x the equivalent Catacombs role. Catacombs
## reference: fodder 14hp/8dmg, swarmer 9/6 spd138, skirmisher 22/10/2armor, raider 38/14/3.

const COL_PALE: Color  = Color(0.82, 0.80, 0.86, 1.0)
const COL_FUNGAL: Color = Color(0.70, 0.85, 0.60, 1.0)
const COL_STONE: Color = Color(0.66, 0.70, 0.78, 1.0)


# ── Melee line ────────────────────────────────────────────────────────────────

static func create_nm_fodder() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_fodder"
	def.enemy_name     = "Giant Rat"
	def.tags           = ["Melee", "Common", "Swarm", "Beast"]
	def.base_stats     = {"max_hp": 20.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 85.0
	def.contact_damage = 10.0
	def.base_armor     = 0.0
	def.xp_value       = 0.9
	def.health_drop_chance   = 0.04
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.3
	def.sprite_scale         = Vector2(0.9, 0.9)
	return def


static func create_nm_swarmer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_swarmer"
	def.enemy_name     = "Dire Wolf"
	def.tags           = ["Melee", "Common", "Swarm", "Beast"]
	def.base_stats     = {"max_hp": 14.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 150.0        ## the biome's fastest — runs the cave bat's role
	def.contact_damage = 9.0
	def.base_armor     = 0.0
	def.xp_value       = 0.8
	def.health_drop_chance   = 0.03
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.5
	return def


static func create_nm_skirmisher() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_skirmisher"
	def.enemy_name     = "Gnoll"
	def.tags           = ["Melee", "Common"]
	def.base_stats     = {"max_hp": 33.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 100.0
	def.contact_damage = 14.0
	def.base_armor     = 3.0
	def.xp_value       = 1.7
	def.health_drop_chance   = 0.06
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.0
	return def


static func create_nm_stalker() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_stalker"
	def.enemy_name     = "Cursed Wanderer"
	def.tags           = ["Melee", "Common"]
	def.base_stats     = {"max_hp": 40.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 92.0
	def.contact_damage = 15.0
	def.base_armor     = 3.0
	def.xp_value       = 2.0
	def.health_drop_chance   = 0.06
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.0
	return def


static func create_nm_raider() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_raider"
	def.enemy_name     = "Deep One"
	def.tags           = ["Melee", "Common"]
	def.base_stats     = {"max_hp": 55.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 66.0
	def.contact_damage = 19.0
	def.base_armor     = 5.0
	def.xp_value       = 2.8
	def.health_drop_chance   = 0.08
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.8
	return def


static func create_nm_ambusher() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_ambusher"
	def.enemy_name     = "Chest Mimic"
	def.tags           = ["Melee", "Ambusher"]
	def.base_stats     = {"max_hp": 46.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 70.0         ## slow, but it hits harder than anything else its size
	def.contact_damage = 22.0
	def.base_armor     = 4.0
	def.xp_value       = 2.4
	def.health_drop_chance   = 0.12   ## it is, after all, a treasure chest
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.7
	return def


## The pack ships the Chest Mimic in two complete, distinct variants. Wiring only the
## Aggressive one would orphan six finished sheets, so the Shy one becomes its own unit:
## quicker and flimsier, the version that bolts rather than brawls.
static func create_nm_lurker() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_lurker"
	def.enemy_name     = "Shy Mimic"
	def.tags           = ["Melee", "Ambusher"]
	def.base_stats     = {"max_hp": 28.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 105.0
	def.contact_damage = 13.0
	def.base_armor     = 2.0
	def.xp_value       = 1.9
	def.health_drop_chance   = 0.12   ## still a treasure chest
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.15
	def.sprite_scale         = Vector2(0.9, 0.9)
	return def


static func create_nm_aerial() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_aerial"
	def.enemy_name     = "Gargoyle"
	def.tags           = ["Melee", "Aerial"]
	def.base_stats     = {"max_hp": 30.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 128.0
	def.contact_damage = 15.0
	def.base_armor     = 2.0
	def.xp_value       = 2.2
	def.health_drop_chance   = 0.05
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.2
	def.base_modulate        = COL_STONE
	return def


static func create_nm_brute() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_brute"
	def.enemy_name     = "Demon Spider"
	def.tags           = ["Melee", "Heavy", "Beast"]
	def.base_stats     = {"max_hp": 95.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 72.0
	def.contact_damage = 26.0
	def.base_armor     = 7.0
	def.xp_value       = 4.0
	def.health_drop_chance   = 0.10
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.55
	return def


static func create_nm_heavy() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_heavy"
	def.enemy_name     = "Giant"
	def.tags           = ["Melee", "Heavy"]
	def.base_stats     = {"max_hp": 150.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 52.0
	def.contact_damage = 34.0
	def.base_armor     = 10.0
	def.xp_value       = 5.5
	def.health_drop_chance   = 0.14
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.3
	return def


# ── Ranged line ───────────────────────────────────────────────────────────────

static func create_nm_archer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_archer"
	def.enemy_name     = "Ratfolk Slinger"
	def.tags           = ["Ranged", "Common"]
	def.base_stats     = {"max_hp": 26.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 58.0
	def.contact_damage = 7.0
	def.base_armor     = 1.0
	def.xp_value       = 2.2
	def.health_drop_chance   = 0.06
	def.behavior_type        = "ranged"
	def.preferred_range      = 175.0
	def.auto_attack = _thrown_attack(
		"nm_refuse",
		PACK + "Rat_People/RubishProjectile.png",
		PACK + "Rat_People/RubishImpact.png",
		13.0, "Physical", 160.0, 175.0, 2.1)
	return def


static func create_nm_caster() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_caster"
	def.enemy_name     = "Brain Slayer"
	def.tags           = ["Ranged", "Caster"]
	def.base_stats     = {"max_hp": 30.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 52.0
	def.contact_damage = 7.0
	def.base_armor     = 0.0
	def.xp_value       = 2.8
	def.health_drop_chance   = 0.07
	def.behavior_type        = "ranged"
	def.preferred_range      = 185.0
	def.auto_attack = _thrown_attack(
		"nm_psychic_bolt",
		PACK + "Brain_Slayer/MagicProjectile.png",
		PACK + "Brain_Slayer/MagicImpact.png",
		18.0, "Void", 135.0, 185.0, 2.6)
	return def


static func create_nm_royal() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_royal"
	def.enemy_name     = "Ratfolk Monarch"
	def.tags           = ["Ranged", "Elite"]
	def.base_stats     = {"max_hp": 44.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 62.0
	def.contact_damage = 9.0
	def.base_armor     = 2.0
	def.xp_value       = 3.4
	def.health_drop_chance   = 0.10
	def.behavior_type        = "ranged"
	def.preferred_range      = 195.0
	## Rat_Landing.png is the thrown rat's arrival, which is exactly an impact anim —
	## it is 4 directional rows, so the impact takes row 0 like every other enemy anim.
	def.auto_attack = _thrown_attack(
		"nm_thrown_rat",
		PACK + "Rat_People_Royalty/Rat_Projectile.png",
		PACK + "Rat_People_Royalty/Rat_Landing.png",
		24.0, "Physical", 150.0, 195.0, 3.0)
	return def


static func create_nm_spore() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "nm_spore"
	def.enemy_name     = "Predatory Mushroom"
	def.tags           = ["Ranged", "Caster"]
	def.base_stats     = {"max_hp": 34.0}
	def.combat_role    = "RANGED"
	## Rooted, not immobile: the pack ships no Walk sheet for it (see the scene generator),
	## and a crawl this slow reads as the fungus dragging itself rather than standing still.
	def.move_speed     = 22.0
	def.contact_damage = 8.0
	def.base_armor     = 2.0
	def.xp_value       = 2.2
	def.health_drop_chance   = 0.07
	def.behavior_type        = "ranged"
	def.preferred_range      = 150.0
	def.auto_attack = _spore_attack(
		"nm_spore_cloud", 15.0, 95.0, 150.0, 2.8)
	def.base_modulate  = COL_FUNGAL
	return def


# ── Projectile builders ───────────────────────────────────────────────────────

const PACK: String = "res://assets/minifantasy/Minifantasy_Monster_Creatures_v1.0/Minifantasy_Monster_Creatures_Assets/"


## All three thrown/cast projectiles in this pack ship as 96x96 sheets — the pack's standard
## 3x3 grid of eight facings around an empty centre, the same shape ChainFactory reads for
## every other single-frame directional projectile (and what the Catacombs archers use).
## Reusing its helper keeps one cell mapping in the codebase instead of two.
static func _thrown_attack(id: String, sheet: String, impact_sheet: String, damage: float,
		damage_type: String, speed: float, range_px: float, cooldown: float) -> AbilityDefinition:
	var config := ProjectileConfig.new()
	config.motion_type = "directional"
	config.speed = speed
	config.max_range = range_px * 1.4
	config.hit_radius = 7.0
	config.sprite_frames = ChainFactory._grid8_frames(sheet, "nightmare_" + id)
	config.use_directional_anims = true
	config.fallback_color = COL_PALE
	config.pierce_count = 0
	## This pack ships a matching impact sheet beside every projectile — wire it, or the
	## projectile vanishes with no punctuation.
	config.impact_sprite_frames = ChainFactory._oneshot_row_frames(impact_sheet, 16.0)
	config.impact_animation = "impact"

	var dmg := DealDamageEffect.new()
	dmg.damage_type = damage_type
	dmg.base_damage = damage
	config.on_hit_effects = [dmg]

	var tags: Array[String] = ["Ranged", "Projectile"]
	return _ability_from(id, config, range_px, cooldown, tags)


## The mushroom has no projectile sheet — Spores_Attack.png is a BODY animation of it
## venting spores. So the cloud itself is procedural (fallback_color, no frames): a slow,
## short-range puff that reads as gas rather than a thrown object.
static func _spore_attack(id: String, damage: float, speed: float,
		range_px: float, cooldown: float) -> AbilityDefinition:
	var config := ProjectileConfig.new()
	config.motion_type = "directional"
	config.speed = speed
	config.max_range = range_px * 1.2
	config.hit_radius = 12.0          ## a cloud, not a dart
	config.use_directional_anims = false
	config.fallback_color = Color(0.62, 0.82, 0.48, 0.85)
	config.pierce_count = 2           ## drifts through a small crowd

	var dmg := DealDamageEffect.new()
	dmg.damage_type = "Poison"
	dmg.base_damage = damage
	config.on_hit_effects = [dmg]

	var tags: Array[String] = ["Ranged", "Projectile"]
	return _ability_from(id, config, range_px, cooldown, tags)


## `tags` is Array[String], not Array: AbilityDefinition.tags is a TYPED array, and assigning
## an untyped one compiles cleanly and then throws at runtime. See the same note in
## crypt_enemy_data.gd — it only surfaced when EnemySpawnManager built the registry in a
## running game, with every static check passing.
static func _ability_from(id: String, config: ProjectileConfig, range_px: float,
		cooldown: float, tags: Array[String]) -> AbilityDefinition:
	var spawn := SpawnProjectilesEffect.new()
	spawn.projectile = config
	spawn.spawn_pattern = "aimed_single"
	spawn.count = 1

	var aa := AbilityDefinition.new()
	aa.ability_id = id
	aa.ability_name = id
	aa.tags = tags
	aa.cooldown_base = cooldown
	aa.mode = "Auto"
	var targeting := TargetingRule.new()
	targeting.type = "nearest_enemy"
	targeting.max_range = range_px * 1.3
	aa.targeting = targeting
	aa.effects = [spawn]
	return aa
