class_name ThresholdEnemyData
extends RefCounted
## Level 4 — The Threshold — enemy definitions.
##
## Two packs, split by depth, because the biome's identity is "someone opened a door they
## could not hold": the shallows are the cult still holding it, the deeps are what came
## through. Minifantasy_Dark_Brotherhood supplies phases 1-3, Minifantasy_Dark_Orc_Army
## supplies phases 4-5, and the Possessed tier is the hinge between them — the cult after
## the thing it summoned got inside it.
##
## Seventeen rank-and-file roles; the miniboss and final boss live in their own factories
## (RitualGuardData / PaleChampionData) because bosses carry choreographed skills.
##
##   ── the cult (Cannon_Fodder) ─────────────────────────────────────────────
##   th_fodder       Acolyte             — fragile melee swarm
##   th_swarmer      Cult Hound          — fastest unit, paper-thin
##   th_zealot       Zealot              — standard melee
##   ── the devoted (Devoted_Brothers) ───────────────────────────────────────
##   th_skirmisher   Devoted Blade       — armoured melee
##   th_sentinel     Devoted Sentinel    — slower, meatier melee
##   th_archer       Devoted Stalker     — ranged, the only real projectile sheet in either pack
##   ── the chosen (Choosen_Ones) ────────────────────────────────────────────
##   th_caster       Dark Channeler      — ranged, void bolt
##   th_flagellant   Flagellant          — high damage, low armour; hurts itself to hurt you
##   ── the possessed (Possessed) ────────────────────────────────────────────
##   th_possessed    Dark Cultist        — the Zealot's role, after
##   th_hound        Dark Hound          — fast AND heavy, which nothing else is
##   th_abomination  Dark Abomination    — brute
##   ── the army (Dark_Orc_Army) ─────────────────────────────────────────────
##   th_raider       Orc Raider          — army melee
##   th_berserker    Warbreed Berserker  — aggressive, fast for its weight
##   th_phalanx      Warbreed Phalanx    — armour wall; the biome's armour check
##   th_arbalist     Warbreed Arbalist   — elite ranged
##   th_warg         Warg                — the army's fast beast
##   th_troll        Cave Troll          — heaviest rank-and-file
##
## Scenes are generated by tools/gen_threshold_scenes.gd. Registered in EnemyRegistry.
##
## Scaling intent: biome 4 sits roughly 1.3x the equivalent Nightmare Realm role. NMRealm
## reference: fodder 20hp/10dmg, swarmer 14/9 spd150, skirmisher 33/14/3armor,
## raider 55/19/5, brute 95/26/7, heavy 150/34/10.
##
## DELIBERATELY UNWIRED SHEETS, and why — the full-utilization rule wants a reason, not
## silence:
##   - Dark_Channeler/Possess_Acolyte, Possess_Hound, Possess_Zealot. These are 2-row
##     sequences of a *named lesser unit* being taken over, i.e. a mid-life transform from
##     one enemy into another. enemy.gd has no transform hook — the same limitation that
##     left the Monster pack's Werewolf/Transformation unwired, where the two shapes
##     shipped as two separate units instead. The Channeler still casts with Possess.png,
##     so the gesture is on screen; only the target-swap is missing.
##   - The whole Feral_Orcs tier, plus Lesser Orc_Blade / Orc_Scout and Warbreed_Blade.
##     The orc pack is three rank tiers of the same four archetypes, so wiring every tier
##     makes late waves read as recolours of early ones. One tier of each silhouette ships;
##     Orc_Raider survives from Lesser because its Bite sheet makes it a different animal.

const COL_ASH: Color   = Color(0.78, 0.76, 0.82, 1.0)
const COL_VOID: Color  = Color(0.58, 0.42, 0.78, 1.0)
const COL_EMBER: Color = Color(0.90, 0.54, 0.38, 1.0)


# ── The cult ──────────────────────────────────────────────────────────────────

static func create_th_fodder() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_fodder"
	def.enemy_name     = "Acolyte"
	def.tags           = ["Melee", "Common", "Swarm", "Cultist"]
	def.base_stats     = {"max_hp": 26.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 88.0
	def.contact_damage = 13.0
	def.base_armor     = 0.0
	def.xp_value       = 1.1
	def.health_drop_chance   = 0.04
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.3
	def.sprite_scale         = Vector2(0.9, 0.9)
	return def


static func create_th_swarmer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_swarmer"
	def.enemy_name     = "Cult Hound"
	def.tags           = ["Melee", "Common", "Swarm", "Beast"]
	def.base_stats     = {"max_hp": 18.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 155.0        ## the biome's fastest, and the phase-1 pressure
	def.contact_damage = 11.0
	def.base_armor     = 0.0
	def.xp_value       = 1.0
	def.health_drop_chance   = 0.03
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.5
	return def


static func create_th_zealot() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_zealot"
	def.enemy_name     = "Zealot"
	def.tags           = ["Melee", "Common", "Cultist"]
	def.base_stats     = {"max_hp": 36.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 100.0
	def.contact_damage = 16.0
	def.base_armor     = 2.0
	def.xp_value       = 1.8
	def.health_drop_chance   = 0.06
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.0
	return def


# ── The devoted ───────────────────────────────────────────────────────────────

static func create_th_skirmisher() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_skirmisher"
	def.enemy_name     = "Devoted Blade"
	def.tags           = ["Melee", "Common", "Cultist"]
	def.base_stats     = {"max_hp": 48.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 98.0
	def.contact_damage = 19.0
	def.base_armor     = 4.0
	def.xp_value       = 2.2
	def.health_drop_chance   = 0.06
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.0
	return def


static func create_th_sentinel() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_sentinel"
	def.enemy_name     = "Devoted Sentinel"
	def.tags           = ["Melee", "Common", "Cultist"]
	def.base_stats     = {"max_hp": 72.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 66.0
	def.contact_damage = 25.0
	def.base_armor     = 7.0
	def.xp_value       = 3.1
	def.health_drop_chance   = 0.08
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.8
	return def


static func create_th_archer() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_archer"
	def.enemy_name     = "Devoted Stalker"
	def.tags           = ["Ranged", "Common", "Cultist"]
	def.base_stats     = {"max_hp": 34.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 60.0
	def.contact_damage = 9.0
	def.base_armor     = 1.0
	def.xp_value       = 2.4
	def.health_drop_chance   = 0.06
	def.behavior_type        = "ranged"
	def.preferred_range      = 180.0
	## The one unit across both packs with a real Shot_Projectile sheet (96x96, the pack's
	## standard 3x3 grid of eight facings around an empty centre).
	def.auto_attack = _sprite_bolt(
		"th_dark_bolt", BROTHERHOOD + "Devoted_Brothers/Devoted_Stalker/Shot_Projectile.png",
		17.0, "Physical", 165.0, 180.0, 2.2)
	return def


# ── The chosen ────────────────────────────────────────────────────────────────

static func create_th_caster() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_caster"
	def.enemy_name     = "Dark Channeler"
	def.tags           = ["Ranged", "Caster", "Cultist"]
	def.base_stats     = {"max_hp": 40.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 54.0
	def.contact_damage = 9.0
	def.base_armor     = 0.0
	def.xp_value       = 3.0
	def.health_drop_chance   = 0.07
	def.behavior_type        = "ranged"
	def.preferred_range      = 190.0
	## Procedural bolt: the Channeler ships no projectile sheet, because the pack's answer
	## to "what does it do at range" is Possess, which needs a transform hook the engine
	## does not have (see the header). Possess.png is still its cast animation, so the
	## gesture reads correctly and only the target-swap is absent.
	def.auto_attack = _procedural_bolt(
		"th_void_lash", 21.0, "Void", Color(0.62, 0.40, 0.86, 0.9),
		8.0, 0, 140.0, 190.0, 2.6)
	def.base_modulate  = COL_VOID
	return def


static func create_th_flagellant() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_flagellant"
	def.enemy_name     = "Flagellant"
	def.tags           = ["Melee", "Elite", "Cultist"]
	def.base_stats     = {"max_hp": 58.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 108.0        ## quick and barely armoured: it does not intend to survive
	def.contact_damage = 28.0
	def.base_armor     = 2.0
	def.xp_value       = 3.3
	def.health_drop_chance   = 0.07
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.1
	return def


# ── The possessed ─────────────────────────────────────────────────────────────

static func create_th_possessed() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_possessed"
	def.enemy_name     = "Dark Cultist"
	def.tags           = ["Melee", "Common", "Possessed"]
	def.base_stats     = {"max_hp": 56.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 95.0
	def.contact_damage = 22.0
	def.base_armor     = 4.0
	def.xp_value       = 2.7
	def.health_drop_chance   = 0.07
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.95
	def.base_modulate        = COL_VOID
	return def


static func create_th_hound() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_hound"
	def.enemy_name     = "Dark Hound"
	def.tags           = ["Melee", "Beast", "Possessed"]
	def.base_stats     = {"max_hp": 48.0}
	def.combat_role    = "MELEE"
	## Fast AND hard-hitting, which nothing else in the roster is. This is the unit that
	## makes phase 4 stop being a matter of walking backwards.
	def.move_speed     = 140.0
	def.contact_damage = 24.0
	def.base_armor     = 2.0
	def.xp_value       = 3.2
	def.health_drop_chance   = 0.06
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.0
	def.base_modulate        = COL_VOID
	return def


static func create_th_abomination() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_abomination"
	def.enemy_name     = "Dark Abomination"
	def.tags           = ["Melee", "Heavy", "Possessed"]
	def.base_stats     = {"max_hp": 124.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 70.0
	def.contact_damage = 34.0
	def.base_armor     = 9.0
	def.xp_value       = 4.6
	def.health_drop_chance   = 0.10
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.55
	return def


# ── The army ──────────────────────────────────────────────────────────────────

static func create_th_raider() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_raider"
	def.enemy_name     = "Orc Raider"
	def.tags           = ["Melee", "Common", "Orc"]
	def.base_stats     = {"max_hp": 62.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 92.0
	def.contact_damage = 23.0
	def.base_armor     = 5.0
	def.xp_value       = 2.9
	def.health_drop_chance   = 0.07
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.9
	return def


static func create_th_berserker() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_berserker"
	def.enemy_name     = "Warbreed Berserker"
	def.tags           = ["Melee", "Elite", "Orc"]
	def.base_stats     = {"max_hp": 88.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 112.0        ## fast for its weight — the army's closer
	def.contact_damage = 32.0
	def.base_armor     = 4.0
	def.xp_value       = 4.0
	def.health_drop_chance   = 0.09
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.7
	return def


static func create_th_phalanx() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_phalanx"
	def.enemy_name     = "Warbreed Phalanx"
	def.tags           = ["Melee", "Heavy", "Orc"]
	def.base_stats     = {"max_hp": 110.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 62.0
	def.contact_damage = 28.0
	## The biome's armour check: 14 is the highest non-boss value in the game, so flat-damage
	## builds stall on it and have to bring conversion or shred.
	def.base_armor     = 14.0
	def.xp_value       = 4.4
	def.health_drop_chance   = 0.10
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.4
	return def


static func create_th_arbalist() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_arbalist"
	def.enemy_name     = "Warbreed Arbalist"
	def.tags           = ["Ranged", "Elite", "Orc"]
	def.base_stats     = {"max_hp": 52.0}
	def.combat_role    = "RANGED"
	def.move_speed     = 62.0
	def.contact_damage = 11.0
	def.base_armor     = 3.0
	def.xp_value       = 3.6
	def.health_drop_chance   = 0.08
	def.behavior_type        = "ranged"
	def.preferred_range      = 205.0
	## Procedural again: the orc pack ships no projectile sheet at all — Shot_Orthogonal and
	## Shot_Diagonal are BODY animations of the crossbow being fired. Fast, small and pale so
	## it reads as a bolt rather than a spell.
	def.auto_attack = _procedural_bolt(
		"th_quarrel", 26.0, "Physical", Color(0.86, 0.84, 0.78, 0.95),
		5.0, 0, 210.0, 205.0, 3.0)
	return def


static func create_th_warg() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_warg"
	def.enemy_name     = "Warg"
	def.tags           = ["Melee", "Swarm", "Beast", "Orc"]
	def.base_stats     = {"max_hp": 44.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 158.0
	def.contact_damage = 20.0
	def.base_armor     = 2.0
	def.xp_value       = 2.8
	def.health_drop_chance   = 0.05
	def.behavior_type        = "chase"
	def.knockback_multiplier = 1.2
	return def


static func create_th_troll() -> EnemyDefinition:
	var def := EnemyDefinition.new()
	def.enemy_id       = "th_troll"
	def.enemy_name     = "Cave Troll"
	def.tags           = ["Melee", "Heavy", "Orc"]
	def.base_stats     = {"max_hp": 195.0}
	def.combat_role    = "MELEE"
	def.move_speed     = 50.0
	def.contact_damage = 44.0
	def.base_armor     = 13.0
	def.xp_value       = 6.2
	def.health_drop_chance   = 0.14
	def.behavior_type        = "chase"
	def.knockback_multiplier = 0.25
	return def


# ── Projectile builders ───────────────────────────────────────────────────────

const BROTHERHOOD: String = "res://assets/minifantasy/Minifantasy_Dark_Brotherhood_v1.0/Dark_Brotherhood/"


## Sprite-backed projectile from a 96x96 sheet — the pack's standard 3x3 grid of eight
## facings around an empty centre, the same shape ChainFactory reads for every other
## single-frame directional projectile. No impact sheet ships with it, so the bolt simply
## expires; ProjectileManager handles an unset impact_sprite_frames.
static func _sprite_bolt(id: String, sheet: String, damage: float, damage_type: String,
		speed: float, range_px: float, cooldown: float) -> AbilityDefinition:
	var config := ProjectileConfig.new()
	config.motion_type = "directional"
	config.speed = speed
	config.max_range = range_px * 1.4
	config.hit_radius = 7.0
	config.sprite_frames = ChainFactory._grid8_frames(sheet, "threshold_" + id)
	config.use_directional_anims = true
	config.fallback_color = COL_ASH
	config.pierce_count = 0

	var dmg := DealDamageEffect.new()
	dmg.damage_type = damage_type
	dmg.base_damage = damage
	config.on_hit_effects = [dmg]

	var tags: Array[String] = ["Ranged", "Projectile"]
	return _ability_from(id, config, range_px, cooldown, tags)


## Frameless projectile for the two shooters whose packs ship only body animations.
## Same treatment the Nightmare Realm's spore cloud got, and for the same reason.
static func _procedural_bolt(id: String, damage: float, damage_type: String, color: Color,
		hit_radius: float, pierce: int, speed: float, range_px: float,
		cooldown: float) -> AbilityDefinition:
	var config := ProjectileConfig.new()
	config.motion_type = "directional"
	config.speed = speed
	config.max_range = range_px * 1.25
	config.hit_radius = hit_radius
	config.use_directional_anims = false
	config.fallback_color = color
	config.pierce_count = pierce

	var dmg := DealDamageEffect.new()
	dmg.damage_type = damage_type
	dmg.base_damage = damage
	config.on_hit_effects = [dmg]

	var tags: Array[String] = ["Ranged", "Projectile"]
	return _ability_from(id, config, range_px, cooldown, tags)


## `tags` is Array[String], not Array: AbilityDefinition.tags is a TYPED array, and assigning
## an untyped one compiles cleanly and then throws at runtime. Same note as
## nightmare_enemy_data.gd and crypt_enemy_data.gd — it only surfaces when EnemySpawnManager
## builds the registry in a running game, with every static check passing.
static func _ability_from(id: String, config: ProjectileConfig, range_px: float,
		cooldown: float, tags: Array[String]) -> AbilityDefinition:
	var spawn := SpawnProjectilesEffect.new()
	spawn.projectile = config
	spawn.spawn_pattern = "aimed_single"
	spawn.count = 1

	var aa := AbilityDefinition.new()
	aa.ability_id = id
	aa.ability_name = id
	aa.tags = tags
	aa.cooldown_base = cooldown
	aa.mode = "Auto"
	var targeting := TargetingRule.new()
	targeting.type = "nearest_enemy"
	targeting.max_range = range_px * 1.3
	aa.targeting = targeting
	aa.effects = [spawn]
	return aa
